"""参数表字段校验规则."""


REQUIRED_SHEET_FIELDS = {
    "Description": [
        "ID",
        "WeatherID",
        "ClimateID",
        "SoilFile",
        "SoilName",
        "Hybrid",
        "VarietyFile",
        "WeatherFileName",
        "ClimateFile",
        "Location",
        "NitrogenFile",
        "Solute",
        "Path",
        "Biology",
        "MulchGeo",
        "MulchDecomp",
        "Gas_File",
        "Gas_CO2",
        "Gas_O2",
        "Gas_N2O",
        "Tillage",
        "WaterMovParam",
    ],
    "Climate": [
        "ClimateID",
        "Location",
        "Latitude",
        "Longitude",
        "DailyBulb",
        "DailyWind",
        "RainIntensity",
        "DailyConc",
        "Furrow",
        "RelHumid",
        "DailyCO2",
        "Bsolar",
        "Btemp",
        "Atemp",
        "Erain",
        "BWind",
        "BIR",
        "AvgWind",
        "AvgRainRate",
        "ChemConc",
        "AvgCO2",
    ],
    "Weather": ["ClimateID", "WeatherID", "Source_name", "Time"],
    "Time": ["ID", "startDate", "EndDate"],
    "Init": [
        "ID",
        "Population(p/ha)",
        "Lat",
        "Long",
        "altitude(m)",
        "sowing",
        "end",
        "autoirrigated",
        "RowAngle",
        "Xseed",
        "seedDepth",
        "CEC",
        "EOMult",
        "RowSpacing(cm)",
    ],
    "Soil": [
        "SoilFile",
        "Bottom depth",
        "Init Type",
        "OM (%/100)",
        "Humus_C",
        "Humus_N",
        "Litter_C",
        "Litter_N",
        "Manure_C",
        "Manure_N",
        "NO3 (ppm)",
        "NH4",
        "HNew",
        "Tmpr",
        "CO2(ppm)",
        "O2(ppm)",
        "N2O(ppm)",
        "Sand",
        "Silt",
        "Clay",
        "BD",
        "TH33",
        "TH1500",
        "kh",
        "kL",
        "km",
        "kn",
        "kd",
        "fe",
        "fh",
        "r0",
        "rL",
        "rm",
        "fa",
        "nq",
        "cs",
        "thr",
        "ths",
        "tha",
        "th",
        "Alfa",
        "n",
        "Ks",
        "Kk",
        "thk",
    ],
    "GridRatio": [
        "SoilFile",
        "SR1",
        "IR1",
        "SR2",
        "IR2",
        "PlantingDepth",
        "XLimitRoot",
        "BottomBC",
        "GasBCTop",
        "GasBCBottom",
        "InitRtMass",
    ],
    "Variety": [
        "Hybrid",
        "JuvenileLeaves",
        "DaylengthSensitive",
        "Rmax_LTAR",
        "Rmax_LTIR",
        "PhyllFrmTassel",
        "StayGreen",
        "LM_min",
        "RRRM",
        "RRRY",
        "RVRL",
        "ALPM",
        "ALPY",
        "RTWL",
        "RTMinWTperArea",
        "EPSI",
        "lUpW",
        "CourMax",
        "Diffx",
        "Diffz",
        "VelZ",
        "Isink",
        "Rroot",
        "ConstI_M",
        "ConstK_M",
        "Cmin0_M",
        "ConstI_Y",
        "ConstK_Y",
        "Cmin0_Y",
    ],
    "Biology": ["ID"],
    "Solute": ["ID", "EPSI", "lUPW", "CourMax", "Diffusion_Coeff"],
    "Gas": ["ID", "EPSI", "bTort", "Diffusion_Coeff(cm2/day)"],
    "MulchGeo": ["ID"],
    "MulchDecomp": ["ID"],
    "WaterMovParam": [
        "ID",
        "MaxIt",
        "TolTh",
        "TolH",
        "hCritA",
        "hCritS",
        "DtMx",
        "htab1",
        "htabN",
        "EPSI.Heat",
        "EPSI.Solute",
    ],
    "Fertilization": [
        "ID",
        "date",
        "amount",
        "depth",
        "Litter_C(kg/ha)",
        "Litter_N",
        "Manure_C",
        "Manure_N",
        "date_residue",
        "type(t or m)",
        "rate (t/ha or  cm)",
        "Vertical Layers",
    ],
    "Tillage": ["ID", "Till(1/0)", "DaysBeforePlanting", "Depth"],
    "Irrig": ["ID", "type", "date_start", "date_end", "amount (mm/day)", "Depth (mm)", "start_hour", "end_hour"],
    "Drip": ["ID", "date", "rate(cm/hr)", "StartTime", "StopTime", "Distance"],
    "DripNodes": ["ID", "nodes"],
}
